// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7umaLvbuh2tbKl6Cd3zz2tgvgg53JAFQ',
    appId: '1:547016938628:web:e264828557ee0aa6379ed1',
    messagingSenderId: '547016938628',
    projectId: 'ridee-app-f0895',
    authDomain: 'ridee-app-f0895.firebaseapp.com',
    storageBucket: 'ridee-app-f0895.appspot.com',
    measurementId: 'G-KZJJS0ZD0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB86vY0ZsimOJP-Bo9zW8hFhZ4l1xmXNVE',
    appId: '1:547016938628:android:a43db4e1f532b8ac379ed1',
    messagingSenderId: '547016938628',
    projectId: 'ridee-app-f0895',
    storageBucket: 'ridee-app-f0895.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtg3w_Z2b2WniAcmdFjdIHGq8YLeotYLk',
    appId: '1:547016938628:ios:e8347fc838985cbd379ed1',
    messagingSenderId: '547016938628',
    projectId: 'ridee-app-f0895',
    storageBucket: 'ridee-app-f0895.appspot.com',
    androidClientId: '547016938628-3frrbqq3t30bcfe97hh9hgg64rhmv6hh.apps.googleusercontent.com',
    iosClientId: '547016938628-6qi98tgsi98pm3lqobhr3k1fam5anp0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.riderRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtg3w_Z2b2WniAcmdFjdIHGq8YLeotYLk',
    appId: '1:547016938628:ios:c7d496d9425d0bc3379ed1',
    messagingSenderId: '547016938628',
    projectId: 'ridee-app-f0895',
    storageBucket: 'ridee-app-f0895.appspot.com',
    iosClientId:
        '547016938628-6qi98tgsi98pm3lqobhr3k1fam5anp0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.riderRegister',
  );
}